services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: photoshare
      POSTGRES_USER: photouser
      POSTGRES_PASSWORD: photopass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
    - backend/src/config/.env 
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${JWT_SECRET_KEY}
      - ALGORITHM=${JWT_ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  default:
    name: photoshare_network